package com.fogacoop.flujofogacoop;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("BodyTiempoEspera")
public class BodyTiempoEspera implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("fechaResultado")
	private java.lang.String fechaResultado;

	@org.kie.api.definition.type.Label(value = "tiempoISO")
	private java.lang.String tiempoISO;

	public BodyTiempoEspera() {
	}

	public java.lang.String getFechaResultado() {
		return this.fechaResultado;
	}

	public void setFechaResultado(java.lang.String fechaResultado) {
		this.fechaResultado = fechaResultado;
	}

	public java.lang.String getTiempoISO() {
		return this.tiempoISO;
	}

	public void setTiempoISO(java.lang.String tiempoISO) {
		this.tiempoISO = tiempoISO;
	}

	public BodyTiempoEspera(java.lang.String fechaResultado,
			java.lang.String tiempoISO) {
		this.fechaResultado = fechaResultado;
		this.tiempoISO = tiempoISO;
	}

}