package com.fogacoop.flujofogacoop;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CalculoFechasGestionMoraDTO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("fechaInicioDiaria")
	private String fechaInicioDiaria;
	@org.kie.api.definition.type.Label("fechaInterrupcionDiaria")
	private String fechaInterrupcionDiaria;
	@org.kie.api.definition.type.Label("tiempoRestanteInterrupcionDiaria")
	private java.lang.String tiempoRestanteInterrupcionDiaria;

	@org.kie.api.definition.type.Label(value = "fechaInicioProceso")
	private java.lang.String fechaInicioProceso;

	public CalculoFechasGestionMoraDTO() {
	}

	public java.lang.String getTiempoRestanteInterrupcionDiaria() {
		return this.tiempoRestanteInterrupcionDiaria;
	}

	public void setTiempoRestanteInterrupcionDiaria(
			java.lang.String tiempoRestanteInterrupcionDiaria) {
		this.tiempoRestanteInterrupcionDiaria = tiempoRestanteInterrupcionDiaria;
	}

	public java.lang.String getFechaInicioDiaria() {
		return this.fechaInicioDiaria;
	}

	public void setFechaInicioDiaria(java.lang.String fechaInicioDiaria) {
		this.fechaInicioDiaria = fechaInicioDiaria;
	}

	public java.lang.String getFechaInterrupcionDiaria() {
		return this.fechaInterrupcionDiaria;
	}

	public void setFechaInterrupcionDiaria(
			java.lang.String fechaInterrupcionDiaria) {
		this.fechaInterrupcionDiaria = fechaInterrupcionDiaria;
	}

	public java.lang.String getFechaInicioProceso() {
		return this.fechaInicioProceso;
	}

	public void setFechaInicioProceso(java.lang.String fechaInicioProceso) {
		this.fechaInicioProceso = fechaInicioProceso;
	}

	public CalculoFechasGestionMoraDTO(java.lang.String fechaInicioDiaria,
			java.lang.String fechaInterrupcionDiaria,
			java.lang.String tiempoRestanteInterrupcionDiaria,
			java.lang.String fechaInicioProceso) {
		this.fechaInicioDiaria = fechaInicioDiaria;
		this.fechaInterrupcionDiaria = fechaInterrupcionDiaria;
		this.tiempoRestanteInterrupcionDiaria = tiempoRestanteInterrupcionDiaria;
		this.fechaInicioProceso = fechaInicioProceso;
	}

}