package com.fogacoop.flujofogacoop;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class consultarListaDominioDto implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "idParametro")
	private java.lang.Integer idParametro;
	@org.kie.api.definition.type.Label(value = "idDominio")
	private java.lang.Integer idDominio;
	@org.kie.api.definition.type.Label(value = "idPadre")
	private java.lang.Integer idPadre;
	@org.kie.api.definition.type.Label(value = "nombre")
	private java.lang.String nombre;
	@org.kie.api.definition.type.Label(value = "valor")
	private java.lang.String valor;
	@org.kie.api.definition.type.Label(value = "descripcion")
	private java.lang.String descripcion;

	public consultarListaDominioDto() {
	}

	public java.lang.Integer getIdParametro() {
		return this.idParametro;
	}

	public void setIdParametro(java.lang.Integer idParametro) {
		this.idParametro = idParametro;
	}

	public java.lang.Integer getIdDominio() {
		return this.idDominio;
	}

	public void setIdDominio(java.lang.Integer idDominio) {
		this.idDominio = idDominio;
	}

	public java.lang.Integer getIdPadre() {
		return this.idPadre;
	}

	public void setIdPadre(java.lang.Integer idPadre) {
		this.idPadre = idPadre;
	}

	public java.lang.String getNombre() {
		return this.nombre;
	}

	public void setNombre(java.lang.String nombre) {
		this.nombre = nombre;
	}

	public java.lang.String getValor() {
		return this.valor;
	}

	public void setValor(java.lang.String valor) {
		this.valor = valor;
	}

	public java.lang.String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(java.lang.String descripcion) {
		this.descripcion = descripcion;
	}

	public consultarListaDominioDto(java.lang.Integer idParametro,
			java.lang.Integer idDominio, java.lang.Integer idPadre,
			java.lang.String nombre, java.lang.String valor,
			java.lang.String descripcion) {
		this.idParametro = idParametro;
		this.idDominio = idDominio;
		this.idPadre = idPadre;
		this.nombre = nombre;
		this.valor = valor;
		this.descripcion = descripcion;
	}

}