package com.fogacoop.flujofogacoop;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RequestGestionarReglaMoraPSDDTO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "conteoDias")
	private java.lang.Integer conteoDias;
	@org.kie.api.definition.type.Label(value = "tokenAutenticatedBusiness")
	private com.fogacoop.flujofogacoop.TokenDTO tokenAutenticatedBusiness;

	public RequestGestionarReglaMoraPSDDTO() {
	}

	public java.lang.Integer getConteoDias() {
		return this.conteoDias;
	}

	public void setConteoDias(java.lang.Integer conteoDias) {
		this.conteoDias = conteoDias;
	}

	public com.fogacoop.flujofogacoop.TokenDTO getTokenAutenticatedBusiness() {
		return this.tokenAutenticatedBusiness;
	}

	public void setTokenAutenticatedBusiness(
			com.fogacoop.flujofogacoop.TokenDTO tokenAutenticatedBusiness) {
		this.tokenAutenticatedBusiness = tokenAutenticatedBusiness;
	}

	public RequestGestionarReglaMoraPSDDTO(java.lang.Integer conteoDias,
			com.fogacoop.flujofogacoop.TokenDTO tokenAutenticatedBusiness) {
		this.conteoDias = conteoDias;
		this.tokenAutenticatedBusiness = tokenAutenticatedBusiness;
	}

}