package com.fogacoop.flujofogacoop;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RequestEnviarPagoRecaudo implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("ownerUser")
	private com.fogacoop.flujofogacoop.OwnerUserDTO ownerUser;
	@org.kie.api.definition.type.Label("basic")
	private RecaudoDTO basic;

	@org.kie.api.definition.type.Label(value = "tokenAutenticatedBusiness")
	private com.fogacoop.flujofogacoop.TokenDTO tokenAutenticatedBusiness;

	public RequestEnviarPagoRecaudo() {
	}

	public com.fogacoop.flujofogacoop.OwnerUserDTO getOwnerUser() {
		return this.ownerUser;
	}

	public void setOwnerUser(com.fogacoop.flujofogacoop.OwnerUserDTO ownerUser) {
		this.ownerUser = ownerUser;
	}

	public com.fogacoop.flujofogacoop.RecaudoDTO getBasic() {
		return this.basic;
	}

	public void setBasic(com.fogacoop.flujofogacoop.RecaudoDTO basic) {
		this.basic = basic;
	}

	public com.fogacoop.flujofogacoop.TokenDTO getTokenAutenticatedBusiness() {
		return this.tokenAutenticatedBusiness;
	}

	public void setTokenAutenticatedBusiness(
			com.fogacoop.flujofogacoop.TokenDTO tokenAutenticatedBusiness) {
		this.tokenAutenticatedBusiness = tokenAutenticatedBusiness;
	}

	public RequestEnviarPagoRecaudo(
			com.fogacoop.flujofogacoop.OwnerUserDTO ownerUser,
			com.fogacoop.flujofogacoop.RecaudoDTO basic,
			com.fogacoop.flujofogacoop.TokenDTO tokenAutenticatedBusiness) {
		this.ownerUser = ownerUser;
		this.basic = basic;
		this.tokenAutenticatedBusiness = tokenAutenticatedBusiness;
	}

}