package com.fogacoop.flujofogacoop;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RequestActualizarPago implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("estadoPago")
	private java.lang.String estadoPago;

	@org.kie.api.definition.type.Label(value = "nroTransaccion")
	private java.lang.String nroTransaccion;

	@org.kie.api.definition.type.Label(value = "tipoPago")
	private java.lang.String tipoPago;

	public RequestActualizarPago() {
	}

	public java.lang.String getEstadoPago() {
		return this.estadoPago;
	}

	public void setEstadoPago(java.lang.String estadoPago) {
		this.estadoPago = estadoPago;
	}

	public java.lang.String getNroTransaccion() {
		return this.nroTransaccion;
	}

	public void setNroTransaccion(java.lang.String nroTransaccion) {
		this.nroTransaccion = nroTransaccion;
	}

	public java.lang.String getTipoPago() {
		return this.tipoPago;
	}

	public void setTipoPago(java.lang.String tipoPago) {
		this.tipoPago = tipoPago;
	}

	public RequestActualizarPago(java.lang.String estadoPago,
			java.lang.String nroTransaccion, java.lang.String tipoPago) {
		this.estadoPago = estadoPago;
		this.nroTransaccion = nroTransaccion;
		this.tipoPago = tipoPago;
	}

}