package com.fogacoop.flujofogacoop;

import com.fogacoop.flujofogacoop.ResponseBaseDto;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ResponseCicloGestionMoraPSDDTO extends ResponseBaseDto
		implements
			java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "body")
	private com.fogacoop.flujofogacoop.BodyCicloGestionMoraPSDDTO body;

	public ResponseCicloGestionMoraPSDDTO() {
	}

	public com.fogacoop.flujofogacoop.BodyCicloGestionMoraPSDDTO getBody() {
		return this.body;
	}

	public void setBody(
			com.fogacoop.flujofogacoop.BodyCicloGestionMoraPSDDTO body) {
		this.body = body;
	}

	public ResponseCicloGestionMoraPSDDTO(
			com.fogacoop.flujofogacoop.BodyCicloGestionMoraPSDDTO body) {
		this.body = body;
	}

}