package com.fogacoop.flujofogacoop;

import com.fogacoop.flujofogacoop.ResponseBaseDto;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ResponseGetTransactionDto extends ResponseBaseDto
		implements
			java.io.Serializable {

	@org.kie.api.definition.type.Label(value = "body")
	private com.fogacoop.flujofogacoop.BodyGetTransactionsDTO body;

	public com.fogacoop.flujofogacoop.BodyGetTransactionsDTO getBody() {
		return this.body;
	}

	public void setBody(com.fogacoop.flujofogacoop.BodyGetTransactionsDTO body) {
		this.body = body;
	}

	public ResponseGetTransactionDto() {
	}

	public ResponseGetTransactionDto(
			com.fogacoop.flujofogacoop.BodyGetTransactionsDTO body) {
		this.body = body;
	}

}