package com.fogacoop.flujofogacoop;

import com.fogacoop.flujofogacoop.ResponseBaseDto;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ResponseConsultarCompararValorDto extends ResponseBaseDto
		implements
			java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "body")
	private com.fogacoop.flujofogacoop.ResultBasicDto body;

	public ResponseConsultarCompararValorDto() {
	}

	public com.fogacoop.flujofogacoop.ResultBasicDto getBody() {
		return this.body;
	}

	public void setBody(com.fogacoop.flujofogacoop.ResultBasicDto body) {
		this.body = body;
	}

	public ResponseConsultarCompararValorDto(
			com.fogacoop.flujofogacoop.ResultBasicDto body) {
		this.body = body;
	}

}