package com.fogacoop.flujofogacoop;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TokenDTO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "tokenBusiness")
	private java.lang.String tokenBusiness;

	public TokenDTO() {
	}

	public java.lang.String getTokenBusiness() {
		return this.tokenBusiness;
	}

	public void setTokenBusiness(java.lang.String tokenBusiness) {
		this.tokenBusiness = tokenBusiness;
	}

	public TokenDTO(java.lang.String tokenBusiness) {
		this.tokenBusiness = tokenBusiness;
	}

}